name: TMMobCoins
version: 1.0
main: net.devtm.tmmobcoins.TMMobCoinsPlugin
author: TMDevelopment
description: Best Mob coins plugin plugin
website: devtm.net
api-version: 1.13

commands:
  tmobcoins:
    description: Main command
  mobcoins:
    description: Mobcoins shop command
